services:
  app:
    #Build on current directory
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    #Mapping out dir to the dir in the container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"